name: deploy to lambda

on:
  push:
    paths:
      - src/handler/**
    branches:
      - dev
  pull_request:
    paths:
      - src/handler/**
    branches:
      - dev

jobs:

  deploy_source:
    name: deploy lambda from source
    runs-on: ubuntu-latest
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          aws_session_token: ${{ secrets.AWS_SESSION_TOKEN }}
          function_name: bf-autodatavideos-handler
          source: src/handler/function.py