name: Deploy crawler of updates to AWS Lambda

on:
  push:
    branches:
      - dev
    paths:
      - src/**
      - '!src/handler/**'
      - '!src/scheduler-tr/**'
      - '!src/crawler/**'
      - '!src/scheduler-rl/**'
  pull_request:
    branches:
      - dev
    paths:
      - src/**
      - '!src/handler/**'
      - '!src/scheduler-tr/**'
      - '!src/crawler/**'
      - '!src/scheduler-rl/**'

jobs:

  deploy_aws_lambda:
    name: Deploy to AWS Lambda from source
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Switch python to 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Rebuild structure
        run: |
          cd src
          cp -r database crawler-lambda/database/
          cp -r core crawler-lambda/core/
          cp config.yml crawler-lambda/config.yml
          cp requirements.txt crawler-lambda/requirements.txt
          cd crawler-lambda
          pip install -r requirements.txt --target ./

      - name: Deploy as update-code via AWS CLI
        uses: jsmrcaga/action-easy-lambda-deploy@v0.0.3
        with:
          function_name: bf-autodatavideos-crawler
          region: ${{ secrets.AWS_REGION }}
          zip_command: cd src/crawler-lambda; zip -r easy-lambda-deploy.zip ./
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}