name: Deploy handler to AWS Lambda

on:
  push:
    branches:
      - dev
    paths:
      - src/**
      - '!src/crawler-rl/**'
      - '!src/crawler-tr/**'
      - '!src/crawler-lambda/**'
  pull_request:
    branches:
      - dev
    paths:
      - src/**
      - '!src/crawler-rl/**'
      - '!src/crawler-tr/**'
      - '!src/crawler-lambda/**'

jobs:

  deploy_aws_lambda:
    name: Deploy to AWS Lambda from source
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Switch python to 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Rebuild structure
        run: |
          cd src
          cp -r database handler/database/
          cp -r core handler/core/
          cp config.yml handler/config.yml
          cp requirements.txt handler/requirements.txt
          cd handler
          pip install -r requirements.txt --target ./

      - name: Deploy as update-code via AWS CLI
        uses: jsmrcaga/action-easy-lambda-deploy@v0.0.3
        with:
          function_name: bf-autodatavideos-handler
          region: ${{ secrets.AWS_REGION }}
          zip_command: cd src/handler; zip -r easy-lambda-deploy.zip ./
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
          AWS_REGION: ${{ secrets.AWS_REGION }}